name: Node CI

on:
  push:
    branches:
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Should this run?
      run: |
        COUNT=$(git diff --name-only HEAD~1 | wc -l)
        if [ $COUNT = 1 ]; then git diff --name-only HEAD~1 | grep README; fi
        if [ $? = 0 ]; then echo 'Only the README has changed, skipping build.'; exit 66; fi
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        tsc --listEmittedFiles
        npm test
      env:
        CI: true
